# Generated by Django 4.1 on 2025-04-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='zip_files/'),
        ),
    ]
