# Generated by Django 4.1 on 2025-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_zipfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfile',
            name='extracted_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
